### ISSUE TITLE
One or more errors with zip/tar files. They were deleted, please try again...

### ISSUE THREAD

**Issue by 2braincells2go** [jyapayne/Electrify#1]
Wouldn't you just know it Joey, I am the one with first issue, lol.

Trying to find info in error message but perhaps I am so new to Electron / Electrify do not know exact issue.

I have loaded a HTML (index,html) project in. Filled out what I think is enough info, chose my output folder and even changed the download settings to c:\Users\Public\Downloads\Electrify just in case write permission error.

When clicking export button, see the software trying download but get error:

![2016-02-09_163733](https://cloud.githubusercontent.com/assets/2567500/12933012/774a0474-cf4b-11e5-9c32-b67e23dd0077.png)

Wonder what I am doing wrong?

Thanks!

**Comment by 2braincells2go** [comment]
Hey Joey, my git is not getting:)

Looks like error in cfg file:

https://github.com/atom/electron/releases/download/v{}/'

**Comment by 2braincells2go** [comment]
Also if you remake the exe's, you must manually remove/delete the old output directory or get write permission error. No biggie, just letting you know.

**Comment by jyapayne** [comment]
:) Of course you are the first issue!

What did you replace the url in the cfg with?

**Comment by 2braincells2go** [comment]
Forget what the URL was, but I changed to:

https://github.com/atom/electron/releases/download/v{}/

**Comment by jyapayne** [comment]
That's interesting. That's exactly what it shows in my version. I have:

https://github.com/atom/electron/releases/download/v{}/

**Comment by jyapayne** [comment]
https://github.com/jyapayne/Electrify/blob/master/files/settings.cfg

**Comment by jyapayne** [comment]
That was the config file you edited, right? The first line?

**Comment by 2braincells2go** [comment]
yes sir. the url that was in when was getting error shown in screenshot. I went to the electron releases and found URL, changed it.

Beats me Joey. I may be going crazy...

and yes, edited first line.

**Comment by jyapayne** [comment]
:) That's very weird.

**Comment by 2braincells2go** [comment]
it is working so we can count this issue as "old man syndrome" and close:)
